#!/bin/bash
#Ben Cradick
#CS 2750
#Project 3

#

permissions(){

    if [ -G  $var ] ; then

	    echo "You have permission to access $var"

    else

	    echo "You do not have permission to access $var"

    fi
}
main(){
    #does file exist
    if [ ! -e $var ] ; then

	echo "$var is not a file"

        exit
    #was there an argument or was -h given as argument
    elif ( [ -z $var ] || [ $var == "-h" ] ); then

        echo "This script takes files and directories as arguments like such \$ ./fileinfo {argument}"
    #is argument special file
    elif ([ -b $var ] || [ -c $var ] || [ -h $var ]); then

        echo "$var is a special file"
    #is it a directory
    elif ([ -d $var ]); then


        echo "$var is a directory" 
        permissions "$var";

    #is it a normal file
    elif [ -f $var ]; then

	echo "$var is a normal file"

    fi   
    #is user the owner
    if [ -O $var ]; then

        echo "You own $var"

    else

	echo "You do not own $var" 

    fi

    have="You have permissions to"
    dont="You do not have permissions to"
    #checking if $USER has permission -r:read -w:write -x:execute if directory (-d) then excluded
    if ( [ -r $var ] ); then

        echo "$have read  $var"

    else

	echo "$dont read $var"

    fi

    if ( [ -w $var  ] ); then

        echo "$have write $var"

    else

	echo "$dont write $var"

    fi

    if ( [ -x $var  ] && [ ! -d $var ] ); then

        echo "$have execute $var"

    elif ( [ ! -x $var ] && [ ! -d $var ] ); then

	echo "$have execute $var"

    fi

    echo ""
}
#loop through all argsS
for var in "$@";do 

    main "$var";

done
