#!/usr/bin/bash
#Ben Cradick
#CS 2750
#Project 3

#this doesn't work on mac but I need to check on CentOS

permissions(){

    if [ -r  $var ] ; then

	    echo "You have permission to access $var"

    else

	    echo "You do not have permission to access $var"

    fi
}
main(){

    if [ ! -e $var ] ; then

	echo "$var is not a file"

        exit

    elif ( [ -z $var ] || [ $var == "-h" ] ); then

        echo "This script takes files and directories as arguments like such \$ ./fileinfo {argument}"

    elif ([ -d $var ] && [ -f $var ]); then


        echo "$var is a directory" 
        permissions "$var";


    elif [ -f $var ]; then

	echo "$var is a normal file"

    fi

    if [ ! -f $var ]; then
     
	echo "$var is a special file."

    fi    

    if [ -O $var ]; then

        echo "You own $var"

    else

	echo "You do not own $var" 

    fi

    have="You have permissions to"
    dont="You do not have permissions to"

    if ( [ -r $var ] ); then

        echo "$have read  $var"

    else

	echo "$dont read $var"

    fi

    if ( [ -w $var  ] ); then

        echo "$have write $var"

    else

	echo "$dont write $var"

    fi

    if ( [ -x $var  ] && [ ! -d $var ] ); then

        echo "$have execute $var"

    elif ( [ ! -x $var ] && [ ! -d $var ] ); then

	echo "$have execute $var"

    fi

    echo ""
}

for var in "$@";do 

    main "$var";

done
