#!/usr/bin/bash
#Ben Cradick
#CS 2750
#Project 1
permissions(){
    if ( ls $var 2> /dev/null ) ; then
	    echo "You have permission to access $var"
    else
	    echo "You do not have permission to access $var"
    fi
}
main(){
    if [ ! -e $var ] ; then
	    echo "$var is not a file"
        exit
    elif ( [ -z $var ] || [ $var == "-h" ] ); then
        echo "This script takes files and directories as arguments like such \$ ./fileinfo arg"
    elif [[ -d $var ]]; then
        echo "$var is a directory" 
        permissions "$var";
    elif [ ! -f $var ]; then
        echo "This is a special file."
    else
	    echo "This is a normal file"
    fi
    echo "Test"
    if ( ls -l $var | grep -q $USER ); then
        echo "You own $var" 
    fi

}

for var in "$@";do 
    main "$var";
done
