#!/bin/bash
#Ben Cradick
#CS 2750
#Project 1
permissions(){
    namei -l ~ | grep $USER
}
main(){
    if [[ -z $var ]] || [ $var == "-h" ]]; then
        echo "This script takes files and directories as arguments like such \$ ./fileinfo arg"
    elif [[ -d $var ]]; then
        echo "This file is a directory"
}

for var in "$@";do 
    main "$var";
done

