#!/usr/bin/bash
#Ben Cradick
#CS 2750
#Project 3

SEDMAGIC='s;[^/]*/;|____;g;s;____|; |;g'

if [ "$#" -gt 0 ] ; then
   dirlist="$@"
else
   dirlist="."
fi
for x in $dirlist; do
     find "$x" -print | sed -e "$SEDMAGIC"
done